//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cit-let_cit">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-book"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Cit-let_man-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Cit-let_type" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="manuscript"/>
 *                       &lt;enumeration value="letter"/>
 *                       &lt;enumeration value="thesis"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "citLetCit",
    "citLetManId",
    "citLetType"
})
@XmlRootElement(name = "Cit-let")
public class CitLet {

    @XmlElement(name = "Cit-let_cit", required = true)
    protected CitLet.CitLetCit citLetCit;
    @XmlElement(name = "Cit-let_man-id")
    protected String citLetManId;
    @XmlElement(name = "Cit-let_type")
    protected CitLet.CitLetType citLetType;

    /**
     * Gets the value of the citLetCit property.
     * 
     * @return
     *     possible object is
     *     {@link CitLet.CitLetCit }
     *     
     */
    public CitLet.CitLetCit getCitLetCit() {
        return citLetCit;
    }

    /**
     * Sets the value of the citLetCit property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitLet.CitLetCit }
     *     
     */
    public void setCitLetCit(CitLet.CitLetCit value) {
        this.citLetCit = value;
    }

    /**
     * Gets the value of the citLetManId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitLetManId() {
        return citLetManId;
    }

    /**
     * Sets the value of the citLetManId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitLetManId(String value) {
        this.citLetManId = value;
    }

    /**
     * Gets the value of the citLetType property.
     * 
     * @return
     *     possible object is
     *     {@link CitLet.CitLetType }
     *     
     */
    public CitLet.CitLetType getCitLetType() {
        return citLetType;
    }

    /**
     * Sets the value of the citLetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitLet.CitLetType }
     *     
     */
    public void setCitLetType(CitLet.CitLetType value) {
        this.citLetType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-book"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "citBook"
    })
    public static class CitLetCit {

        @XmlElement(name = "Cit-book", required = true)
        protected CitBook citBook;

        /**
         * Gets the value of the citBook property.
         * 
         * @return
         *     possible object is
         *     {@link CitBook }
         *     
         */
        public CitBook getCitBook() {
            return citBook;
        }

        /**
         * Sets the value of the citBook property.
         * 
         * @param value
         *     allowed object is
         *     {@link CitBook }
         *     
         */
        public void setCitBook(CitBook value) {
            this.citBook = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="manuscript"/>
     *             &lt;enumeration value="letter"/>
     *             &lt;enumeration value="thesis"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CitLetType {

        @XmlAttribute(name = "value", required = true)
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
