//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Dbtag_db" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Dbtag_tag">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Object-id"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbtagDb",
    "dbtagTag"
})
@XmlRootElement(name = "Dbtag")
public class Dbtag {

    @XmlElement(name = "Dbtag_db", required = true)
    protected String dbtagDb;
    @XmlElement(name = "Dbtag_tag", required = true)
    protected Dbtag.DbtagTag dbtagTag;

    /**
     * Gets the value of the dbtagDb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtagDb() {
        return dbtagDb;
    }

    /**
     * Sets the value of the dbtagDb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtagDb(String value) {
        this.dbtagDb = value;
    }

    /**
     * Gets the value of the dbtagTag property.
     * 
     * @return
     *     possible object is
     *     {@link Dbtag.DbtagTag }
     *     
     */
    public Dbtag.DbtagTag getDbtagTag() {
        return dbtagTag;
    }

    /**
     * Sets the value of the dbtagTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dbtag.DbtagTag }
     *     
     */
    public void setDbtagTag(Dbtag.DbtagTag value) {
        this.dbtagTag = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Object-id"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "objectId"
    })
    public static class DbtagTag {

        @XmlElement(name = "Object-id", required = true)
        protected ObjectId objectId;

        /**
         * Gets the value of the objectId property.
         * 
         * @return
         *     possible object is
         *     {@link ObjectId }
         *     
         */
        public ObjectId getObjectId() {
            return objectId;
        }

        /**
         * Sets the value of the objectId property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObjectId }
         *     
         */
        public void setObjectId(ObjectId value) {
            this.objectId = value;
        }

    }

}
