//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Dense-seg_dim" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Dense-seg_numseg" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Dense-seg_ids">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Seq-id"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Dense-seg_starts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Dense-seg_starts_E" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Dense-seg_lens">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Dense-seg_lens_E" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Dense-seg_strands" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Na-strand"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Dense-seg_scores" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Score"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "denseSegDim",
    "denseSegNumseg",
    "denseSegIds",
    "denseSegStarts",
    "denseSegLens",
    "denseSegStrands",
    "denseSegScores"
})
@XmlRootElement(name = "Dense-seg")
public class DenseSeg {

    @XmlElement(name = "Dense-seg_dim", required = true, defaultValue = "2")
    protected BigInteger denseSegDim;
    @XmlElement(name = "Dense-seg_numseg", required = true)
    protected BigInteger denseSegNumseg;
    @XmlElement(name = "Dense-seg_ids", required = true)
    protected DenseSeg.DenseSegIds denseSegIds;
    @XmlElement(name = "Dense-seg_starts", required = true)
    protected DenseSeg.DenseSegStarts denseSegStarts;
    @XmlElement(name = "Dense-seg_lens", required = true)
    protected DenseSeg.DenseSegLens denseSegLens;
    @XmlElement(name = "Dense-seg_strands")
    protected DenseSeg.DenseSegStrands denseSegStrands;
    @XmlElement(name = "Dense-seg_scores")
    protected DenseSeg.DenseSegScores denseSegScores;

    /**
     * Gets the value of the denseSegDim property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDenseSegDim() {
        return denseSegDim;
    }

    /**
     * Sets the value of the denseSegDim property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDenseSegDim(BigInteger value) {
        this.denseSegDim = value;
    }

    /**
     * Gets the value of the denseSegNumseg property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDenseSegNumseg() {
        return denseSegNumseg;
    }

    /**
     * Sets the value of the denseSegNumseg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDenseSegNumseg(BigInteger value) {
        this.denseSegNumseg = value;
    }

    /**
     * Gets the value of the denseSegIds property.
     * 
     * @return
     *     possible object is
     *     {@link DenseSeg.DenseSegIds }
     *     
     */
    public DenseSeg.DenseSegIds getDenseSegIds() {
        return denseSegIds;
    }

    /**
     * Sets the value of the denseSegIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link DenseSeg.DenseSegIds }
     *     
     */
    public void setDenseSegIds(DenseSeg.DenseSegIds value) {
        this.denseSegIds = value;
    }

    /**
     * Gets the value of the denseSegStarts property.
     * 
     * @return
     *     possible object is
     *     {@link DenseSeg.DenseSegStarts }
     *     
     */
    public DenseSeg.DenseSegStarts getDenseSegStarts() {
        return denseSegStarts;
    }

    /**
     * Sets the value of the denseSegStarts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DenseSeg.DenseSegStarts }
     *     
     */
    public void setDenseSegStarts(DenseSeg.DenseSegStarts value) {
        this.denseSegStarts = value;
    }

    /**
     * Gets the value of the denseSegLens property.
     * 
     * @return
     *     possible object is
     *     {@link DenseSeg.DenseSegLens }
     *     
     */
    public DenseSeg.DenseSegLens getDenseSegLens() {
        return denseSegLens;
    }

    /**
     * Sets the value of the denseSegLens property.
     * 
     * @param value
     *     allowed object is
     *     {@link DenseSeg.DenseSegLens }
     *     
     */
    public void setDenseSegLens(DenseSeg.DenseSegLens value) {
        this.denseSegLens = value;
    }

    /**
     * Gets the value of the denseSegStrands property.
     * 
     * @return
     *     possible object is
     *     {@link DenseSeg.DenseSegStrands }
     *     
     */
    public DenseSeg.DenseSegStrands getDenseSegStrands() {
        return denseSegStrands;
    }

    /**
     * Sets the value of the denseSegStrands property.
     * 
     * @param value
     *     allowed object is
     *     {@link DenseSeg.DenseSegStrands }
     *     
     */
    public void setDenseSegStrands(DenseSeg.DenseSegStrands value) {
        this.denseSegStrands = value;
    }

    /**
     * Gets the value of the denseSegScores property.
     * 
     * @return
     *     possible object is
     *     {@link DenseSeg.DenseSegScores }
     *     
     */
    public DenseSeg.DenseSegScores getDenseSegScores() {
        return denseSegScores;
    }

    /**
     * Sets the value of the denseSegScores property.
     * 
     * @param value
     *     allowed object is
     *     {@link DenseSeg.DenseSegScores }
     *     
     */
    public void setDenseSegScores(DenseSeg.DenseSegScores value) {
        this.denseSegScores = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Seq-id"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "seqId"
    })
    public static class DenseSegIds {

        @XmlElement(name = "Seq-id")
        protected List<SeqId> seqId;

        /**
         * Gets the value of the seqId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the seqId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSeqId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SeqId }
         * 
         * 
         */
        public List<SeqId> getSeqId() {
            if (seqId == null) {
                seqId = new ArrayList<SeqId>();
            }
            return this.seqId;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Dense-seg_lens_E" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "denseSegLensE"
    })
    public static class DenseSegLens {

        @XmlElement(name = "Dense-seg_lens_E")
        protected List<BigInteger> denseSegLensE;

        /**
         * Gets the value of the denseSegLensE property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the denseSegLensE property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDenseSegLensE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BigInteger }
         * 
         * 
         */
        public List<BigInteger> getDenseSegLensE() {
            if (denseSegLensE == null) {
                denseSegLensE = new ArrayList<BigInteger>();
            }
            return this.denseSegLensE;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Score"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "score"
    })
    public static class DenseSegScores {

        @XmlElement(name = "Score")
        protected List<Score> score;

        /**
         * Gets the value of the score property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the score property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getScore().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Score }
         * 
         * 
         */
        public List<Score> getScore() {
            if (score == null) {
                score = new ArrayList<Score>();
            }
            return this.score;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Dense-seg_starts_E" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "denseSegStartsE"
    })
    public static class DenseSegStarts {

        @XmlElement(name = "Dense-seg_starts_E")
        protected List<BigInteger> denseSegStartsE;

        /**
         * Gets the value of the denseSegStartsE property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the denseSegStartsE property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDenseSegStartsE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BigInteger }
         * 
         * 
         */
        public List<BigInteger> getDenseSegStartsE() {
            if (denseSegStartsE == null) {
                denseSegStartsE = new ArrayList<BigInteger>();
            }
            return this.denseSegStartsE;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Na-strand"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naStrand"
    })
    public static class DenseSegStrands {

        @XmlElement(name = "Na-strand")
        protected List<NaStrand> naStrand;

        /**
         * Gets the value of the naStrand property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the naStrand property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNaStrand().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NaStrand }
         * 
         * 
         */
        public List<NaStrand> getNaStrand() {
            if (naStrand == null) {
                naStrand = new ArrayList<NaStrand>();
            }
            return this.naStrand;
        }

    }

}
