//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EMBL-xref_dbname">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}EMBL-dbname"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EMBL-xref_id">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Object-id"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "emblXrefDbname",
    "emblXrefId"
})
@XmlRootElement(name = "EMBL-xref")
public class EMBLXref {

    @XmlElement(name = "EMBL-xref_dbname", required = true)
    protected EMBLXref.EMBLXrefDbname emblXrefDbname;
    @XmlElement(name = "EMBL-xref_id", required = true)
    protected EMBLXref.EMBLXrefId emblXrefId;

    /**
     * Gets the value of the emblXrefDbname property.
     * 
     * @return
     *     possible object is
     *     {@link EMBLXref.EMBLXrefDbname }
     *     
     */
    public EMBLXref.EMBLXrefDbname getEMBLXrefDbname() {
        return emblXrefDbname;
    }

    /**
     * Sets the value of the emblXrefDbname property.
     * 
     * @param value
     *     allowed object is
     *     {@link EMBLXref.EMBLXrefDbname }
     *     
     */
    public void setEMBLXrefDbname(EMBLXref.EMBLXrefDbname value) {
        this.emblXrefDbname = value;
    }

    /**
     * Gets the value of the emblXrefId property.
     * 
     * @return
     *     possible object is
     *     {@link EMBLXref.EMBLXrefId }
     *     
     */
    public EMBLXref.EMBLXrefId getEMBLXrefId() {
        return emblXrefId;
    }

    /**
     * Sets the value of the emblXrefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EMBLXref.EMBLXrefId }
     *     
     */
    public void setEMBLXrefId(EMBLXref.EMBLXrefId value) {
        this.emblXrefId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}EMBL-dbname"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "emblDbname"
    })
    public static class EMBLXrefDbname {

        @XmlElement(name = "EMBL-dbname", required = true)
        protected EMBLDbname emblDbname;

        /**
         * Gets the value of the emblDbname property.
         * 
         * @return
         *     possible object is
         *     {@link EMBLDbname }
         *     
         */
        public EMBLDbname getEMBLDbname() {
            return emblDbname;
        }

        /**
         * Sets the value of the emblDbname property.
         * 
         * @param value
         *     allowed object is
         *     {@link EMBLDbname }
         *     
         */
        public void setEMBLDbname(EMBLDbname value) {
            this.emblDbname = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Object-id"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "objectId"
    })
    public static class EMBLXrefId {

        @XmlElement(name = "Object-id")
        protected List<ObjectId> objectId;

        /**
         * Gets the value of the objectId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the objectId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObjectId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObjectId }
         * 
         * 
         */
        public List<ObjectId> getObjectId() {
            if (objectId == null) {
                objectId = new ArrayList<ObjectId>();
            }
            return this.objectId;
        }

    }

}
