//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 11:55:22 AM PDT 
//


package gov.nih.nlm.ncbi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GBAltSeqData_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GBAltSeqData_items" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}GBAltSeqItem"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gbAltSeqDataName",
    "gbAltSeqDataItems"
})
@XmlRootElement(name = "GBAltSeqData")
public class GBAltSeqData {

    @XmlElement(name = "GBAltSeqData_name", required = true)
    protected String gbAltSeqDataName;
    @XmlElement(name = "GBAltSeqData_items")
    protected GBAltSeqData.GBAltSeqDataItems gbAltSeqDataItems;

    /**
     * Gets the value of the gbAltSeqDataName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBAltSeqDataName() {
        return gbAltSeqDataName;
    }

    /**
     * Sets the value of the gbAltSeqDataName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBAltSeqDataName(String value) {
        this.gbAltSeqDataName = value;
    }

    /**
     * Gets the value of the gbAltSeqDataItems property.
     * 
     * @return
     *     possible object is
     *     {@link GBAltSeqData.GBAltSeqDataItems }
     *     
     */
    public GBAltSeqData.GBAltSeqDataItems getGBAltSeqDataItems() {
        return gbAltSeqDataItems;
    }

    /**
     * Sets the value of the gbAltSeqDataItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link GBAltSeqData.GBAltSeqDataItems }
     *     
     */
    public void setGBAltSeqDataItems(GBAltSeqData.GBAltSeqDataItems value) {
        this.gbAltSeqDataItems = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}GBAltSeqItem"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gbAltSeqItem"
    })
    public static class GBAltSeqDataItems {

        @XmlElement(name = "GBAltSeqItem")
        protected List<GBAltSeqItem> gbAltSeqItem;

        /**
         * Gets the value of the gbAltSeqItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the gbAltSeqItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGBAltSeqItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GBAltSeqItem }
         * 
         * 
         */
        public List<GBAltSeqItem> getGBAltSeqItem() {
            if (gbAltSeqItem == null) {
                gbAltSeqItem = new ArrayList<GBAltSeqItem>();
            }
            return this.gbAltSeqItem;
        }

    }

}
