//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 11:55:22 AM PDT 
//


package gov.nih.nlm.ncbi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GBStrucComment_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GBStrucComment_items">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}GBStrucCommentItem"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gbStrucCommentName",
    "gbStrucCommentItems"
})
@XmlRootElement(name = "GBStrucComment")
public class GBStrucComment {

    @XmlElement(name = "GBStrucComment_name")
    protected String gbStrucCommentName;
    @XmlElement(name = "GBStrucComment_items", required = true)
    protected GBStrucComment.GBStrucCommentItems gbStrucCommentItems;

    /**
     * Gets the value of the gbStrucCommentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBStrucCommentName() {
        return gbStrucCommentName;
    }

    /**
     * Sets the value of the gbStrucCommentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBStrucCommentName(String value) {
        this.gbStrucCommentName = value;
    }

    /**
     * Gets the value of the gbStrucCommentItems property.
     * 
     * @return
     *     possible object is
     *     {@link GBStrucComment.GBStrucCommentItems }
     *     
     */
    public GBStrucComment.GBStrucCommentItems getGBStrucCommentItems() {
        return gbStrucCommentItems;
    }

    /**
     * Sets the value of the gbStrucCommentItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link GBStrucComment.GBStrucCommentItems }
     *     
     */
    public void setGBStrucCommentItems(GBStrucComment.GBStrucCommentItems value) {
        this.gbStrucCommentItems = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}GBStrucCommentItem"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gbStrucCommentItem"
    })
    public static class GBStrucCommentItems {

        @XmlElement(name = "GBStrucCommentItem")
        protected List<GBStrucCommentItem> gbStrucCommentItem;

        /**
         * Gets the value of the gbStrucCommentItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the gbStrucCommentItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGBStrucCommentItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GBStrucCommentItem }
         * 
         * 
         */
        public List<GBStrucCommentItem> getGBStrucCommentItem() {
            if (gbStrucCommentItem == null) {
                gbStrucCommentItem = new ArrayList<GBStrucCommentItem>();
            }
            return this.gbStrucCommentItem;
        }

    }

}
