//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 11:55:22 AM PDT 
//


package gov.nih.nlm.ncbi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GBXref_dbname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GBXref_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gbXrefDbname",
    "gbXrefId"
})
@XmlRootElement(name = "GBXref")
public class GBXref {

    @XmlElement(name = "GBXref_dbname", required = true)
    protected String gbXrefDbname;
    @XmlElement(name = "GBXref_id", required = true)
    protected String gbXrefId;

    /**
     * Gets the value of the gbXrefDbname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBXrefDbname() {
        return gbXrefDbname;
    }

    /**
     * Sets the value of the gbXrefDbname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBXrefDbname(String value) {
        this.gbXrefDbname = value;
    }

    /**
     * Gets the value of the gbXrefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBXrefId() {
        return gbXrefId;
    }

    /**
     * Sets the value of the gbXrefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBXrefId(String value) {
        this.gbXrefId = value;
    }

}
