//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Imprint_date">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Imprint_volume" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Imprint_issue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Imprint_pages" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Imprint_section" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Imprint_pub" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Affil"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Imprint_cprt" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Imprint_part-sup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Imprint_language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Imprint_prepub" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="submitted"/>
 *                       &lt;enumeration value="in-press"/>
 *                       &lt;enumeration value="other"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Imprint_part-supi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Imprint_retract" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}CitRetract"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Imprint_pubstatus" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}PubStatus"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Imprint_history" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}PubStatusDateSet"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imprintDate",
    "imprintVolume",
    "imprintIssue",
    "imprintPages",
    "imprintSection",
    "imprintPub",
    "imprintCprt",
    "imprintPartSup",
    "imprintLanguage",
    "imprintPrepub",
    "imprintPartSupi",
    "imprintRetract",
    "imprintPubstatus",
    "imprintHistory"
})
@XmlRootElement(name = "Imprint")
public class Imprint {

    @XmlElement(name = "Imprint_date", required = true)
    protected Imprint.ImprintDate imprintDate;
    @XmlElement(name = "Imprint_volume")
    protected String imprintVolume;
    @XmlElement(name = "Imprint_issue")
    protected String imprintIssue;
    @XmlElement(name = "Imprint_pages")
    protected String imprintPages;
    @XmlElement(name = "Imprint_section")
    protected String imprintSection;
    @XmlElement(name = "Imprint_pub")
    protected Imprint.ImprintPub imprintPub;
    @XmlElement(name = "Imprint_cprt")
    protected Imprint.ImprintCprt imprintCprt;
    @XmlElement(name = "Imprint_part-sup")
    protected String imprintPartSup;
    @XmlElement(name = "Imprint_language", required = true, defaultValue = "ENG")
    protected String imprintLanguage;
    @XmlElement(name = "Imprint_prepub")
    protected Imprint.ImprintPrepub imprintPrepub;
    @XmlElement(name = "Imprint_part-supi")
    protected String imprintPartSupi;
    @XmlElement(name = "Imprint_retract")
    protected Imprint.ImprintRetract imprintRetract;
    @XmlElement(name = "Imprint_pubstatus")
    protected Imprint.ImprintPubstatus imprintPubstatus;
    @XmlElement(name = "Imprint_history")
    protected Imprint.ImprintHistory imprintHistory;

    /**
     * Gets the value of the imprintDate property.
     * 
     * @return
     *     possible object is
     *     {@link Imprint.ImprintDate }
     *     
     */
    public Imprint.ImprintDate getImprintDate() {
        return imprintDate;
    }

    /**
     * Sets the value of the imprintDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imprint.ImprintDate }
     *     
     */
    public void setImprintDate(Imprint.ImprintDate value) {
        this.imprintDate = value;
    }

    /**
     * Gets the value of the imprintVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImprintVolume() {
        return imprintVolume;
    }

    /**
     * Sets the value of the imprintVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImprintVolume(String value) {
        this.imprintVolume = value;
    }

    /**
     * Gets the value of the imprintIssue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImprintIssue() {
        return imprintIssue;
    }

    /**
     * Sets the value of the imprintIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImprintIssue(String value) {
        this.imprintIssue = value;
    }

    /**
     * Gets the value of the imprintPages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImprintPages() {
        return imprintPages;
    }

    /**
     * Sets the value of the imprintPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImprintPages(String value) {
        this.imprintPages = value;
    }

    /**
     * Gets the value of the imprintSection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImprintSection() {
        return imprintSection;
    }

    /**
     * Sets the value of the imprintSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImprintSection(String value) {
        this.imprintSection = value;
    }

    /**
     * Gets the value of the imprintPub property.
     * 
     * @return
     *     possible object is
     *     {@link Imprint.ImprintPub }
     *     
     */
    public Imprint.ImprintPub getImprintPub() {
        return imprintPub;
    }

    /**
     * Sets the value of the imprintPub property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imprint.ImprintPub }
     *     
     */
    public void setImprintPub(Imprint.ImprintPub value) {
        this.imprintPub = value;
    }

    /**
     * Gets the value of the imprintCprt property.
     * 
     * @return
     *     possible object is
     *     {@link Imprint.ImprintCprt }
     *     
     */
    public Imprint.ImprintCprt getImprintCprt() {
        return imprintCprt;
    }

    /**
     * Sets the value of the imprintCprt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imprint.ImprintCprt }
     *     
     */
    public void setImprintCprt(Imprint.ImprintCprt value) {
        this.imprintCprt = value;
    }

    /**
     * Gets the value of the imprintPartSup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImprintPartSup() {
        return imprintPartSup;
    }

    /**
     * Sets the value of the imprintPartSup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImprintPartSup(String value) {
        this.imprintPartSup = value;
    }

    /**
     * Gets the value of the imprintLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImprintLanguage() {
        return imprintLanguage;
    }

    /**
     * Sets the value of the imprintLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImprintLanguage(String value) {
        this.imprintLanguage = value;
    }

    /**
     * Gets the value of the imprintPrepub property.
     * 
     * @return
     *     possible object is
     *     {@link Imprint.ImprintPrepub }
     *     
     */
    public Imprint.ImprintPrepub getImprintPrepub() {
        return imprintPrepub;
    }

    /**
     * Sets the value of the imprintPrepub property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imprint.ImprintPrepub }
     *     
     */
    public void setImprintPrepub(Imprint.ImprintPrepub value) {
        this.imprintPrepub = value;
    }

    /**
     * Gets the value of the imprintPartSupi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImprintPartSupi() {
        return imprintPartSupi;
    }

    /**
     * Sets the value of the imprintPartSupi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImprintPartSupi(String value) {
        this.imprintPartSupi = value;
    }

    /**
     * Gets the value of the imprintRetract property.
     * 
     * @return
     *     possible object is
     *     {@link Imprint.ImprintRetract }
     *     
     */
    public Imprint.ImprintRetract getImprintRetract() {
        return imprintRetract;
    }

    /**
     * Sets the value of the imprintRetract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imprint.ImprintRetract }
     *     
     */
    public void setImprintRetract(Imprint.ImprintRetract value) {
        this.imprintRetract = value;
    }

    /**
     * Gets the value of the imprintPubstatus property.
     * 
     * @return
     *     possible object is
     *     {@link Imprint.ImprintPubstatus }
     *     
     */
    public Imprint.ImprintPubstatus getImprintPubstatus() {
        return imprintPubstatus;
    }

    /**
     * Sets the value of the imprintPubstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imprint.ImprintPubstatus }
     *     
     */
    public void setImprintPubstatus(Imprint.ImprintPubstatus value) {
        this.imprintPubstatus = value;
    }

    /**
     * Gets the value of the imprintHistory property.
     * 
     * @return
     *     possible object is
     *     {@link Imprint.ImprintHistory }
     *     
     */
    public Imprint.ImprintHistory getImprintHistory() {
        return imprintHistory;
    }

    /**
     * Sets the value of the imprintHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imprint.ImprintHistory }
     *     
     */
    public void setImprintHistory(Imprint.ImprintHistory value) {
        this.imprintHistory = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "date"
    })
    public static class ImprintCprt {

        @XmlElement(name = "Date", required = true)
        protected Date date;

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link Date }
         *     
         */
        public Date getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link Date }
         *     
         */
        public void setDate(Date value) {
            this.date = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "date"
    })
    public static class ImprintDate {

        @XmlElement(name = "Date", required = true)
        protected Date date;

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link Date }
         *     
         */
        public Date getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link Date }
         *     
         */
        public void setDate(Date value) {
            this.date = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}PubStatusDateSet"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pubStatusDateSet"
    })
    public static class ImprintHistory {

        @XmlElement(name = "PubStatusDateSet", required = true)
        protected PubStatusDateSet pubStatusDateSet;

        /**
         * Gets the value of the pubStatusDateSet property.
         * 
         * @return
         *     possible object is
         *     {@link PubStatusDateSet }
         *     
         */
        public PubStatusDateSet getPubStatusDateSet() {
            return pubStatusDateSet;
        }

        /**
         * Sets the value of the pubStatusDateSet property.
         * 
         * @param value
         *     allowed object is
         *     {@link PubStatusDateSet }
         *     
         */
        public void setPubStatusDateSet(PubStatusDateSet value) {
            this.pubStatusDateSet = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="submitted"/>
     *             &lt;enumeration value="in-press"/>
     *             &lt;enumeration value="other"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ImprintPrepub {

        @XmlAttribute(name = "value", required = true)
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Affil"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "affil"
    })
    public static class ImprintPub {

        @XmlElement(name = "Affil", required = true)
        protected Affil affil;

        /**
         * Gets the value of the affil property.
         * 
         * @return
         *     possible object is
         *     {@link Affil }
         *     
         */
        public Affil getAffil() {
            return affil;
        }

        /**
         * Sets the value of the affil property.
         * 
         * @param value
         *     allowed object is
         *     {@link Affil }
         *     
         */
        public void setAffil(Affil value) {
            this.affil = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}PubStatus"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pubStatus"
    })
    public static class ImprintPubstatus {

        @XmlElement(name = "PubStatus", required = true)
        protected PubStatus pubStatus;

        /**
         * Gets the value of the pubStatus property.
         * 
         * @return
         *     possible object is
         *     {@link PubStatus }
         *     
         */
        public PubStatus getPubStatus() {
            return pubStatus;
        }

        /**
         * Sets the value of the pubStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link PubStatus }
         *     
         */
        public void setPubStatus(PubStatus value) {
            this.pubStatus = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}CitRetract"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "citRetract"
    })
    public static class ImprintRetract {

        @XmlElement(name = "CitRetract", required = true)
        protected CitRetract citRetract;

        /**
         * Gets the value of the citRetract property.
         * 
         * @return
         *     possible object is
         *     {@link CitRetract }
         *     
         */
        public CitRetract getCitRetract() {
            return citRetract;
        }

        /**
         * Sets the value of the citRetract property.
         * 
         * @param value
         *     allowed object is
         *     {@link CitRetract }
         *     
         */
        public void setCitRetract(CitRetract value) {
            this.citRetract = value;
        }

    }

}
