//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name-std_last" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name-std_first" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name-std_middle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name-std_full" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name-std_initials" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name-std_suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name-std_title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameStdLast",
    "nameStdFirst",
    "nameStdMiddle",
    "nameStdFull",
    "nameStdInitials",
    "nameStdSuffix",
    "nameStdTitle"
})
@XmlRootElement(name = "Name-std")
public class NameStd {

    @XmlElement(name = "Name-std_last", required = true)
    protected String nameStdLast;
    @XmlElement(name = "Name-std_first")
    protected String nameStdFirst;
    @XmlElement(name = "Name-std_middle")
    protected String nameStdMiddle;
    @XmlElement(name = "Name-std_full")
    protected String nameStdFull;
    @XmlElement(name = "Name-std_initials")
    protected String nameStdInitials;
    @XmlElement(name = "Name-std_suffix")
    protected String nameStdSuffix;
    @XmlElement(name = "Name-std_title")
    protected String nameStdTitle;

    /**
     * Gets the value of the nameStdLast property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameStdLast() {
        return nameStdLast;
    }

    /**
     * Sets the value of the nameStdLast property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameStdLast(String value) {
        this.nameStdLast = value;
    }

    /**
     * Gets the value of the nameStdFirst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameStdFirst() {
        return nameStdFirst;
    }

    /**
     * Sets the value of the nameStdFirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameStdFirst(String value) {
        this.nameStdFirst = value;
    }

    /**
     * Gets the value of the nameStdMiddle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameStdMiddle() {
        return nameStdMiddle;
    }

    /**
     * Sets the value of the nameStdMiddle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameStdMiddle(String value) {
        this.nameStdMiddle = value;
    }

    /**
     * Gets the value of the nameStdFull property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameStdFull() {
        return nameStdFull;
    }

    /**
     * Sets the value of the nameStdFull property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameStdFull(String value) {
        this.nameStdFull = value;
    }

    /**
     * Gets the value of the nameStdInitials property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameStdInitials() {
        return nameStdInitials;
    }

    /**
     * Sets the value of the nameStdInitials property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameStdInitials(String value) {
        this.nameStdInitials = value;
    }

    /**
     * Gets the value of the nameStdSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameStdSuffix() {
        return nameStdSuffix;
    }

    /**
     * Sets the value of the nameStdSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameStdSuffix(String value) {
        this.nameStdSuffix = value;
    }

    /**
     * Gets the value of the nameStdTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameStdTitle() {
        return nameStdTitle;
    }

    /**
     * Sets the value of the nameStdTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameStdTitle(String value) {
        this.nameStdTitle = value;
    }

}
