//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Population-data_population" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Population-data_genotype-frequency" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Population-data_chromosomes-tested" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Population-data_sample-ids" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Object-id"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Population-data_allele-frequency" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Population-data_flags" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
 *                 &lt;attribute name="value">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="is-default-population"/>
 *                       &lt;enumeration value="is-minor-allele"/>
 *                       &lt;enumeration value="is-rare-allele"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "populationDataPopulation",
    "populationDataGenotypeFrequency",
    "populationDataChromosomesTested",
    "populationDataSampleIds",
    "populationDataAlleleFrequency",
    "populationDataFlags"
})
@XmlRootElement(name = "Population-data")
public class PopulationData {

    @XmlElement(name = "Population-data_population", required = true)
    protected String populationDataPopulation;
    @XmlElement(name = "Population-data_genotype-frequency")
    protected Double populationDataGenotypeFrequency;
    @XmlElement(name = "Population-data_chromosomes-tested")
    protected BigInteger populationDataChromosomesTested;
    @XmlElement(name = "Population-data_sample-ids")
    protected PopulationData.PopulationDataSampleIds populationDataSampleIds;
    @XmlElement(name = "Population-data_allele-frequency")
    protected Double populationDataAlleleFrequency;
    @XmlElement(name = "Population-data_flags")
    protected PopulationData.PopulationDataFlags populationDataFlags;

    /**
     * Gets the value of the populationDataPopulation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPopulationDataPopulation() {
        return populationDataPopulation;
    }

    /**
     * Sets the value of the populationDataPopulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPopulationDataPopulation(String value) {
        this.populationDataPopulation = value;
    }

    /**
     * Gets the value of the populationDataGenotypeFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPopulationDataGenotypeFrequency() {
        return populationDataGenotypeFrequency;
    }

    /**
     * Sets the value of the populationDataGenotypeFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPopulationDataGenotypeFrequency(Double value) {
        this.populationDataGenotypeFrequency = value;
    }

    /**
     * Gets the value of the populationDataChromosomesTested property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPopulationDataChromosomesTested() {
        return populationDataChromosomesTested;
    }

    /**
     * Sets the value of the populationDataChromosomesTested property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPopulationDataChromosomesTested(BigInteger value) {
        this.populationDataChromosomesTested = value;
    }

    /**
     * Gets the value of the populationDataSampleIds property.
     * 
     * @return
     *     possible object is
     *     {@link PopulationData.PopulationDataSampleIds }
     *     
     */
    public PopulationData.PopulationDataSampleIds getPopulationDataSampleIds() {
        return populationDataSampleIds;
    }

    /**
     * Sets the value of the populationDataSampleIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopulationData.PopulationDataSampleIds }
     *     
     */
    public void setPopulationDataSampleIds(PopulationData.PopulationDataSampleIds value) {
        this.populationDataSampleIds = value;
    }

    /**
     * Gets the value of the populationDataAlleleFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPopulationDataAlleleFrequency() {
        return populationDataAlleleFrequency;
    }

    /**
     * Sets the value of the populationDataAlleleFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPopulationDataAlleleFrequency(Double value) {
        this.populationDataAlleleFrequency = value;
    }

    /**
     * Gets the value of the populationDataFlags property.
     * 
     * @return
     *     possible object is
     *     {@link PopulationData.PopulationDataFlags }
     *     
     */
    public PopulationData.PopulationDataFlags getPopulationDataFlags() {
        return populationDataFlags;
    }

    /**
     * Sets the value of the populationDataFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopulationData.PopulationDataFlags }
     *     
     */
    public void setPopulationDataFlags(PopulationData.PopulationDataFlags value) {
        this.populationDataFlags = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
     *       &lt;attribute name="value">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="is-default-population"/>
     *             &lt;enumeration value="is-minor-allele"/>
     *             &lt;enumeration value="is-rare-allele"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PopulationDataFlags {

        @XmlValue
        protected BigInteger value;
        @XmlAttribute(name = "value")
        protected String valueAttribute;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the valueAttribute property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValueAttribute() {
            return valueAttribute;
        }

        /**
         * Sets the value of the valueAttribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValueAttribute(String value) {
            this.valueAttribute = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Object-id"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "objectId"
    })
    public static class PopulationDataSampleIds {

        @XmlElement(name = "Object-id")
        protected List<ObjectId> objectId;

        /**
         * Gets the value of the objectId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the objectId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObjectId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObjectId }
         * 
         * 
         */
        public List<ObjectId> getObjectId() {
            if (objectId == null) {
                objectId = new ArrayList<ObjectId>();
            }
            return this.objectId;
        }

    }

}
