//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PRF-block_extra-src" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}PRF-ExtraSrc"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PRF-block_keywords" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="PRF-block_keywords_E" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prfBlockExtraSrc",
    "prfBlockKeywords"
})
@XmlRootElement(name = "PRF-block")
public class PRFBlock {

    @XmlElement(name = "PRF-block_extra-src")
    protected PRFBlock.PRFBlockExtraSrc prfBlockExtraSrc;
    @XmlElement(name = "PRF-block_keywords")
    protected PRFBlock.PRFBlockKeywords prfBlockKeywords;

    /**
     * Gets the value of the prfBlockExtraSrc property.
     * 
     * @return
     *     possible object is
     *     {@link PRFBlock.PRFBlockExtraSrc }
     *     
     */
    public PRFBlock.PRFBlockExtraSrc getPRFBlockExtraSrc() {
        return prfBlockExtraSrc;
    }

    /**
     * Sets the value of the prfBlockExtraSrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRFBlock.PRFBlockExtraSrc }
     *     
     */
    public void setPRFBlockExtraSrc(PRFBlock.PRFBlockExtraSrc value) {
        this.prfBlockExtraSrc = value;
    }

    /**
     * Gets the value of the prfBlockKeywords property.
     * 
     * @return
     *     possible object is
     *     {@link PRFBlock.PRFBlockKeywords }
     *     
     */
    public PRFBlock.PRFBlockKeywords getPRFBlockKeywords() {
        return prfBlockKeywords;
    }

    /**
     * Sets the value of the prfBlockKeywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRFBlock.PRFBlockKeywords }
     *     
     */
    public void setPRFBlockKeywords(PRFBlock.PRFBlockKeywords value) {
        this.prfBlockKeywords = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}PRF-ExtraSrc"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prfExtraSrc"
    })
    public static class PRFBlockExtraSrc {

        @XmlElement(name = "PRF-ExtraSrc", required = true)
        protected PRFExtraSrc prfExtraSrc;

        /**
         * Gets the value of the prfExtraSrc property.
         * 
         * @return
         *     possible object is
         *     {@link PRFExtraSrc }
         *     
         */
        public PRFExtraSrc getPRFExtraSrc() {
            return prfExtraSrc;
        }

        /**
         * Sets the value of the prfExtraSrc property.
         * 
         * @param value
         *     allowed object is
         *     {@link PRFExtraSrc }
         *     
         */
        public void setPRFExtraSrc(PRFExtraSrc value) {
            this.prfExtraSrc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="PRF-block_keywords_E" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prfBlockKeywordsE"
    })
    public static class PRFBlockKeywords {

        @XmlElement(name = "PRF-block_keywords_E")
        protected List<String> prfBlockKeywordsE;

        /**
         * Gets the value of the prfBlockKeywordsE property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the prfBlockKeywordsE property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPRFBlockKeywordsE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPRFBlockKeywordsE() {
            if (prfBlockKeywordsE == null) {
                prfBlockKeywordsE = new ArrayList<String>();
            }
            return this.prfBlockKeywordsE;
        }

    }

}
