//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Program-id_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Program-id_version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "programIdName",
    "programIdVersion"
})
@XmlRootElement(name = "Program-id")
public class ProgramId {

    @XmlElement(name = "Program-id_name", required = true)
    protected String programIdName;
    @XmlElement(name = "Program-id_version")
    protected String programIdVersion;

    /**
     * Gets the value of the programIdName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramIdName() {
        return programIdName;
    }

    /**
     * Sets the value of the programIdName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramIdName(String value) {
        this.programIdName = value;
    }

    /**
     * Gets the value of the programIdVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramIdVersion() {
        return programIdVersion;
    }

    /**
     * Sets the value of the programIdVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramIdVersion(String value) {
        this.programIdVersion = value;
    }

}
