//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Prot-ref_name" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Prot-ref_name_E" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Prot-ref_desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Prot-ref_ec" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Prot-ref_ec_E" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Prot-ref_activity" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Prot-ref_activity_E" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Prot-ref_db" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Dbtag"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Prot-ref_processed" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" default="not-set">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="not-set"/>
 *                       &lt;enumeration value="preprotein"/>
 *                       &lt;enumeration value="mature"/>
 *                       &lt;enumeration value="signal-peptide"/>
 *                       &lt;enumeration value="transit-peptide"/>
 *                       &lt;enumeration value="propeptide"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "protRefName",
    "protRefDesc",
    "protRefEc",
    "protRefActivity",
    "protRefDb",
    "protRefProcessed"
})
@XmlRootElement(name = "Prot-ref")
public class ProtRef {

    @XmlElement(name = "Prot-ref_name")
    protected ProtRef.ProtRefName protRefName;
    @XmlElement(name = "Prot-ref_desc")
    protected String protRefDesc;
    @XmlElement(name = "Prot-ref_ec")
    protected ProtRef.ProtRefEc protRefEc;
    @XmlElement(name = "Prot-ref_activity")
    protected ProtRef.ProtRefActivity protRefActivity;
    @XmlElement(name = "Prot-ref_db")
    protected ProtRef.ProtRefDb protRefDb;
    @XmlElement(name = "Prot-ref_processed")
    protected ProtRef.ProtRefProcessed protRefProcessed;

    /**
     * Gets the value of the protRefName property.
     * 
     * @return
     *     possible object is
     *     {@link ProtRef.ProtRefName }
     *     
     */
    public ProtRef.ProtRefName getProtRefName() {
        return protRefName;
    }

    /**
     * Sets the value of the protRefName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtRef.ProtRefName }
     *     
     */
    public void setProtRefName(ProtRef.ProtRefName value) {
        this.protRefName = value;
    }

    /**
     * Gets the value of the protRefDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtRefDesc() {
        return protRefDesc;
    }

    /**
     * Sets the value of the protRefDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtRefDesc(String value) {
        this.protRefDesc = value;
    }

    /**
     * Gets the value of the protRefEc property.
     * 
     * @return
     *     possible object is
     *     {@link ProtRef.ProtRefEc }
     *     
     */
    public ProtRef.ProtRefEc getProtRefEc() {
        return protRefEc;
    }

    /**
     * Sets the value of the protRefEc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtRef.ProtRefEc }
     *     
     */
    public void setProtRefEc(ProtRef.ProtRefEc value) {
        this.protRefEc = value;
    }

    /**
     * Gets the value of the protRefActivity property.
     * 
     * @return
     *     possible object is
     *     {@link ProtRef.ProtRefActivity }
     *     
     */
    public ProtRef.ProtRefActivity getProtRefActivity() {
        return protRefActivity;
    }

    /**
     * Sets the value of the protRefActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtRef.ProtRefActivity }
     *     
     */
    public void setProtRefActivity(ProtRef.ProtRefActivity value) {
        this.protRefActivity = value;
    }

    /**
     * Gets the value of the protRefDb property.
     * 
     * @return
     *     possible object is
     *     {@link ProtRef.ProtRefDb }
     *     
     */
    public ProtRef.ProtRefDb getProtRefDb() {
        return protRefDb;
    }

    /**
     * Sets the value of the protRefDb property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtRef.ProtRefDb }
     *     
     */
    public void setProtRefDb(ProtRef.ProtRefDb value) {
        this.protRefDb = value;
    }

    /**
     * Gets the value of the protRefProcessed property.
     * 
     * @return
     *     possible object is
     *     {@link ProtRef.ProtRefProcessed }
     *     
     */
    public ProtRef.ProtRefProcessed getProtRefProcessed() {
        return protRefProcessed;
    }

    /**
     * Sets the value of the protRefProcessed property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtRef.ProtRefProcessed }
     *     
     */
    public void setProtRefProcessed(ProtRef.ProtRefProcessed value) {
        this.protRefProcessed = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Prot-ref_activity_E" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "protRefActivityE"
    })
    public static class ProtRefActivity {

        @XmlElement(name = "Prot-ref_activity_E")
        protected List<String> protRefActivityE;

        /**
         * Gets the value of the protRefActivityE property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the protRefActivityE property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProtRefActivityE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getProtRefActivityE() {
            if (protRefActivityE == null) {
                protRefActivityE = new ArrayList<String>();
            }
            return this.protRefActivityE;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Dbtag"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dbtag"
    })
    public static class ProtRefDb {

        @XmlElement(name = "Dbtag")
        protected List<Dbtag> dbtag;

        /**
         * Gets the value of the dbtag property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dbtag property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDbtag().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dbtag }
         * 
         * 
         */
        public List<Dbtag> getDbtag() {
            if (dbtag == null) {
                dbtag = new ArrayList<Dbtag>();
            }
            return this.dbtag;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Prot-ref_ec_E" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "protRefEcE"
    })
    public static class ProtRefEc {

        @XmlElement(name = "Prot-ref_ec_E")
        protected List<String> protRefEcE;

        /**
         * Gets the value of the protRefEcE property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the protRefEcE property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProtRefEcE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getProtRefEcE() {
            if (protRefEcE == null) {
                protRefEcE = new ArrayList<String>();
            }
            return this.protRefEcE;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Prot-ref_name_E" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "protRefNameE"
    })
    public static class ProtRefName {

        @XmlElement(name = "Prot-ref_name_E")
        protected List<String> protRefNameE;

        /**
         * Gets the value of the protRefNameE property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the protRefNameE property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProtRefNameE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getProtRefNameE() {
            if (protRefNameE == null) {
                protRefNameE = new ArrayList<String>();
            }
            return this.protRefNameE;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" default="not-set">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="not-set"/>
     *             &lt;enumeration value="preprotein"/>
     *             &lt;enumeration value="mature"/>
     *             &lt;enumeration value="signal-peptide"/>
     *             &lt;enumeration value="transit-peptide"/>
     *             &lt;enumeration value="propeptide"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ProtRefProcessed {

        @XmlAttribute(name = "value")
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            if (value == null) {
                return "not-set";
            } else {
                return value;
            }
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
