//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Pub_gen">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-gen"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pub_sub">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-sub"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pub_medline">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Medline-entry"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pub_muid" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Pub_article">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-art"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pub_journal">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-jour"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pub_book">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-book"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pub_proc">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-proc"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pub_patent">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-pat"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pub_pat-id">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Id-pat"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pub_man">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-let"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pub_equiv">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Pub-equiv"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pub_pmid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}PubMedId"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pubGen",
    "pubSub",
    "pubMedline",
    "pubMuid",
    "pubArticle",
    "pubJournal",
    "pubBook",
    "pubProc",
    "pubPatent",
    "pubPatId",
    "pubMan",
    "pubEquiv",
    "pubPmid"
})
@XmlRootElement(name = "Pub")
public class Pub {

    @XmlElement(name = "Pub_gen")
    protected Pub.PubGen pubGen;
    @XmlElement(name = "Pub_sub")
    protected Pub.PubSub pubSub;
    @XmlElement(name = "Pub_medline")
    protected Pub.PubMedline pubMedline;
    @XmlElement(name = "Pub_muid")
    protected BigInteger pubMuid;
    @XmlElement(name = "Pub_article")
    protected Pub.PubArticle pubArticle;
    @XmlElement(name = "Pub_journal")
    protected Pub.PubJournal pubJournal;
    @XmlElement(name = "Pub_book")
    protected Pub.PubBook pubBook;
    @XmlElement(name = "Pub_proc")
    protected Pub.PubProc pubProc;
    @XmlElement(name = "Pub_patent")
    protected Pub.PubPatent pubPatent;
    @XmlElement(name = "Pub_pat-id")
    protected Pub.PubPatId pubPatId;
    @XmlElement(name = "Pub_man")
    protected Pub.PubMan pubMan;
    @XmlElement(name = "Pub_equiv")
    protected Pub.PubEquiv pubEquiv;
    @XmlElement(name = "Pub_pmid")
    protected Pub.PubPmid pubPmid;

    /**
     * Gets the value of the pubGen property.
     * 
     * @return
     *     possible object is
     *     {@link Pub.PubGen }
     *     
     */
    public Pub.PubGen getPubGen() {
        return pubGen;
    }

    /**
     * Sets the value of the pubGen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pub.PubGen }
     *     
     */
    public void setPubGen(Pub.PubGen value) {
        this.pubGen = value;
    }

    /**
     * Gets the value of the pubSub property.
     * 
     * @return
     *     possible object is
     *     {@link Pub.PubSub }
     *     
     */
    public Pub.PubSub getPubSub() {
        return pubSub;
    }

    /**
     * Sets the value of the pubSub property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pub.PubSub }
     *     
     */
    public void setPubSub(Pub.PubSub value) {
        this.pubSub = value;
    }

    /**
     * Gets the value of the pubMedline property.
     * 
     * @return
     *     possible object is
     *     {@link Pub.PubMedline }
     *     
     */
    public Pub.PubMedline getPubMedline() {
        return pubMedline;
    }

    /**
     * Sets the value of the pubMedline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pub.PubMedline }
     *     
     */
    public void setPubMedline(Pub.PubMedline value) {
        this.pubMedline = value;
    }

    /**
     * Gets the value of the pubMuid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPubMuid() {
        return pubMuid;
    }

    /**
     * Sets the value of the pubMuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPubMuid(BigInteger value) {
        this.pubMuid = value;
    }

    /**
     * Gets the value of the pubArticle property.
     * 
     * @return
     *     possible object is
     *     {@link Pub.PubArticle }
     *     
     */
    public Pub.PubArticle getPubArticle() {
        return pubArticle;
    }

    /**
     * Sets the value of the pubArticle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pub.PubArticle }
     *     
     */
    public void setPubArticle(Pub.PubArticle value) {
        this.pubArticle = value;
    }

    /**
     * Gets the value of the pubJournal property.
     * 
     * @return
     *     possible object is
     *     {@link Pub.PubJournal }
     *     
     */
    public Pub.PubJournal getPubJournal() {
        return pubJournal;
    }

    /**
     * Sets the value of the pubJournal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pub.PubJournal }
     *     
     */
    public void setPubJournal(Pub.PubJournal value) {
        this.pubJournal = value;
    }

    /**
     * Gets the value of the pubBook property.
     * 
     * @return
     *     possible object is
     *     {@link Pub.PubBook }
     *     
     */
    public Pub.PubBook getPubBook() {
        return pubBook;
    }

    /**
     * Sets the value of the pubBook property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pub.PubBook }
     *     
     */
    public void setPubBook(Pub.PubBook value) {
        this.pubBook = value;
    }

    /**
     * Gets the value of the pubProc property.
     * 
     * @return
     *     possible object is
     *     {@link Pub.PubProc }
     *     
     */
    public Pub.PubProc getPubProc() {
        return pubProc;
    }

    /**
     * Sets the value of the pubProc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pub.PubProc }
     *     
     */
    public void setPubProc(Pub.PubProc value) {
        this.pubProc = value;
    }

    /**
     * Gets the value of the pubPatent property.
     * 
     * @return
     *     possible object is
     *     {@link Pub.PubPatent }
     *     
     */
    public Pub.PubPatent getPubPatent() {
        return pubPatent;
    }

    /**
     * Sets the value of the pubPatent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pub.PubPatent }
     *     
     */
    public void setPubPatent(Pub.PubPatent value) {
        this.pubPatent = value;
    }

    /**
     * Gets the value of the pubPatId property.
     * 
     * @return
     *     possible object is
     *     {@link Pub.PubPatId }
     *     
     */
    public Pub.PubPatId getPubPatId() {
        return pubPatId;
    }

    /**
     * Sets the value of the pubPatId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pub.PubPatId }
     *     
     */
    public void setPubPatId(Pub.PubPatId value) {
        this.pubPatId = value;
    }

    /**
     * Gets the value of the pubMan property.
     * 
     * @return
     *     possible object is
     *     {@link Pub.PubMan }
     *     
     */
    public Pub.PubMan getPubMan() {
        return pubMan;
    }

    /**
     * Sets the value of the pubMan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pub.PubMan }
     *     
     */
    public void setPubMan(Pub.PubMan value) {
        this.pubMan = value;
    }

    /**
     * Gets the value of the pubEquiv property.
     * 
     * @return
     *     possible object is
     *     {@link Pub.PubEquiv }
     *     
     */
    public Pub.PubEquiv getPubEquiv() {
        return pubEquiv;
    }

    /**
     * Sets the value of the pubEquiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pub.PubEquiv }
     *     
     */
    public void setPubEquiv(Pub.PubEquiv value) {
        this.pubEquiv = value;
    }

    /**
     * Gets the value of the pubPmid property.
     * 
     * @return
     *     possible object is
     *     {@link Pub.PubPmid }
     *     
     */
    public Pub.PubPmid getPubPmid() {
        return pubPmid;
    }

    /**
     * Sets the value of the pubPmid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pub.PubPmid }
     *     
     */
    public void setPubPmid(Pub.PubPmid value) {
        this.pubPmid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-art"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "citArt"
    })
    public static class PubArticle {

        @XmlElement(name = "Cit-art", required = true)
        protected CitArt citArt;

        /**
         * Gets the value of the citArt property.
         * 
         * @return
         *     possible object is
         *     {@link CitArt }
         *     
         */
        public CitArt getCitArt() {
            return citArt;
        }

        /**
         * Sets the value of the citArt property.
         * 
         * @param value
         *     allowed object is
         *     {@link CitArt }
         *     
         */
        public void setCitArt(CitArt value) {
            this.citArt = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-book"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "citBook"
    })
    public static class PubBook {

        @XmlElement(name = "Cit-book", required = true)
        protected CitBook citBook;

        /**
         * Gets the value of the citBook property.
         * 
         * @return
         *     possible object is
         *     {@link CitBook }
         *     
         */
        public CitBook getCitBook() {
            return citBook;
        }

        /**
         * Sets the value of the citBook property.
         * 
         * @param value
         *     allowed object is
         *     {@link CitBook }
         *     
         */
        public void setCitBook(CitBook value) {
            this.citBook = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Pub-equiv"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pubEquiv"
    })
    public static class PubEquiv {

        @XmlElement(name = "Pub-equiv", required = true)
        protected gov.nih.nlm.ncbi.PubEquiv pubEquiv;

        /**
         * Gets the value of the pubEquiv property.
         * 
         * @return
         *     possible object is
         *     {@link gov.nih.nlm.ncbi.PubEquiv }
         *     
         */
        public gov.nih.nlm.ncbi.PubEquiv getPubEquiv() {
            return pubEquiv;
        }

        /**
         * Sets the value of the pubEquiv property.
         * 
         * @param value
         *     allowed object is
         *     {@link gov.nih.nlm.ncbi.PubEquiv }
         *     
         */
        public void setPubEquiv(gov.nih.nlm.ncbi.PubEquiv value) {
            this.pubEquiv = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-gen"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "citGen"
    })
    public static class PubGen {

        @XmlElement(name = "Cit-gen", required = true)
        protected CitGen citGen;

        /**
         * Gets the value of the citGen property.
         * 
         * @return
         *     possible object is
         *     {@link CitGen }
         *     
         */
        public CitGen getCitGen() {
            return citGen;
        }

        /**
         * Sets the value of the citGen property.
         * 
         * @param value
         *     allowed object is
         *     {@link CitGen }
         *     
         */
        public void setCitGen(CitGen value) {
            this.citGen = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-jour"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "citJour"
    })
    public static class PubJournal {

        @XmlElement(name = "Cit-jour", required = true)
        protected CitJour citJour;

        /**
         * Gets the value of the citJour property.
         * 
         * @return
         *     possible object is
         *     {@link CitJour }
         *     
         */
        public CitJour getCitJour() {
            return citJour;
        }

        /**
         * Sets the value of the citJour property.
         * 
         * @param value
         *     allowed object is
         *     {@link CitJour }
         *     
         */
        public void setCitJour(CitJour value) {
            this.citJour = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-let"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "citLet"
    })
    public static class PubMan {

        @XmlElement(name = "Cit-let", required = true)
        protected CitLet citLet;

        /**
         * Gets the value of the citLet property.
         * 
         * @return
         *     possible object is
         *     {@link CitLet }
         *     
         */
        public CitLet getCitLet() {
            return citLet;
        }

        /**
         * Sets the value of the citLet property.
         * 
         * @param value
         *     allowed object is
         *     {@link CitLet }
         *     
         */
        public void setCitLet(CitLet value) {
            this.citLet = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Medline-entry"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "medlineEntry"
    })
    public static class PubMedline {

        @XmlElement(name = "Medline-entry", required = true)
        protected MedlineEntry medlineEntry;

        /**
         * Gets the value of the medlineEntry property.
         * 
         * @return
         *     possible object is
         *     {@link MedlineEntry }
         *     
         */
        public MedlineEntry getMedlineEntry() {
            return medlineEntry;
        }

        /**
         * Sets the value of the medlineEntry property.
         * 
         * @param value
         *     allowed object is
         *     {@link MedlineEntry }
         *     
         */
        public void setMedlineEntry(MedlineEntry value) {
            this.medlineEntry = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Id-pat"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idPat"
    })
    public static class PubPatId {

        @XmlElement(name = "Id-pat", required = true)
        protected IdPat idPat;

        /**
         * Gets the value of the idPat property.
         * 
         * @return
         *     possible object is
         *     {@link IdPat }
         *     
         */
        public IdPat getIdPat() {
            return idPat;
        }

        /**
         * Sets the value of the idPat property.
         * 
         * @param value
         *     allowed object is
         *     {@link IdPat }
         *     
         */
        public void setIdPat(IdPat value) {
            this.idPat = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-pat"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "citPat"
    })
    public static class PubPatent {

        @XmlElement(name = "Cit-pat", required = true)
        protected CitPat citPat;

        /**
         * Gets the value of the citPat property.
         * 
         * @return
         *     possible object is
         *     {@link CitPat }
         *     
         */
        public CitPat getCitPat() {
            return citPat;
        }

        /**
         * Sets the value of the citPat property.
         * 
         * @param value
         *     allowed object is
         *     {@link CitPat }
         *     
         */
        public void setCitPat(CitPat value) {
            this.citPat = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}PubMedId"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pubMedId"
    })
    public static class PubPmid {

        @XmlElement(name = "PubMedId", required = true)
        protected BigInteger pubMedId;

        /**
         * Gets the value of the pubMedId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPubMedId() {
            return pubMedId;
        }

        /**
         * Sets the value of the pubMedId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPubMedId(BigInteger value) {
            this.pubMedId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-proc"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "citProc"
    })
    public static class PubProc {

        @XmlElement(name = "Cit-proc", required = true)
        protected CitProc citProc;

        /**
         * Gets the value of the citProc property.
         * 
         * @return
         *     possible object is
         *     {@link CitProc }
         *     
         */
        public CitProc getCitProc() {
            return citProc;
        }

        /**
         * Sets the value of the citProc property.
         * 
         * @param value
         *     allowed object is
         *     {@link CitProc }
         *     
         */
        public void setCitProc(CitProc value) {
            this.citProc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Cit-sub"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "citSub"
    })
    public static class PubSub {

        @XmlElement(name = "Cit-sub", required = true)
        protected CitSub citSub;

        /**
         * Gets the value of the citSub property.
         * 
         * @return
         *     possible object is
         *     {@link CitSub }
         *     
         */
        public CitSub getCitSub() {
            return citSub;
        }

        /**
         * Sets the value of the citSub property.
         * 
         * @param value
         *     allowed object is
         *     {@link CitSub }
         *     
         */
        public void setCitSub(CitSub value) {
            this.citSub = value;
        }

    }

}
