//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RNA-qual_qual" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RNA-qual_val" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rnaQualQual",
    "rnaQualVal"
})
@XmlRootElement(name = "RNA-qual")
public class RNAQual {

    @XmlElement(name = "RNA-qual_qual", required = true)
    protected String rnaQualQual;
    @XmlElement(name = "RNA-qual_val", required = true)
    protected String rnaQualVal;

    /**
     * Gets the value of the rnaQualQual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRNAQualQual() {
        return rnaQualQual;
    }

    /**
     * Sets the value of the rnaQualQual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRNAQualQual(String value) {
        this.rnaQualQual = value;
    }

    /**
     * Gets the value of the rnaQualVal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRNAQualVal() {
        return rnaQualVal;
    }

    /**
     * Sets the value of the rnaQualVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRNAQualVal(String value) {
        this.rnaQualVal = value;
    }

}
