//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RNA-ref_type">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="unknown"/>
 *                       &lt;enumeration value="premsg"/>
 *                       &lt;enumeration value="mRNA"/>
 *                       &lt;enumeration value="tRNA"/>
 *                       &lt;enumeration value="rRNA"/>
 *                       &lt;enumeration value="snRNA"/>
 *                       &lt;enumeration value="scRNA"/>
 *                       &lt;enumeration value="snoRNA"/>
 *                       &lt;enumeration value="ncRNA"/>
 *                       &lt;enumeration value="tmRNA"/>
 *                       &lt;enumeration value="miscRNA"/>
 *                       &lt;enumeration value="other"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RNA-ref_pseudo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="true"/>
 *                       &lt;enumeration value="false"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RNA-ref_ext" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="RNA-ref_ext_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RNA-ref_ext_tRNA">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.ncbi.nlm.nih.gov}Trna-ext"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RNA-ref_ext_gen">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.ncbi.nlm.nih.gov}RNA-gen"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rnaRefType",
    "rnaRefPseudo",
    "rnaRefExt"
})
@XmlRootElement(name = "RNA-ref")
public class RNARef {

    @XmlElement(name = "RNA-ref_type", required = true)
    protected RNARef.RNARefType rnaRefType;
    @XmlElement(name = "RNA-ref_pseudo")
    protected RNARef.RNARefPseudo rnaRefPseudo;
    @XmlElement(name = "RNA-ref_ext")
    protected RNARef.RNARefExt rnaRefExt;

    /**
     * Gets the value of the rnaRefType property.
     * 
     * @return
     *     possible object is
     *     {@link RNARef.RNARefType }
     *     
     */
    public RNARef.RNARefType getRNARefType() {
        return rnaRefType;
    }

    /**
     * Sets the value of the rnaRefType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RNARef.RNARefType }
     *     
     */
    public void setRNARefType(RNARef.RNARefType value) {
        this.rnaRefType = value;
    }

    /**
     * Gets the value of the rnaRefPseudo property.
     * 
     * @return
     *     possible object is
     *     {@link RNARef.RNARefPseudo }
     *     
     */
    public RNARef.RNARefPseudo getRNARefPseudo() {
        return rnaRefPseudo;
    }

    /**
     * Sets the value of the rnaRefPseudo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RNARef.RNARefPseudo }
     *     
     */
    public void setRNARefPseudo(RNARef.RNARefPseudo value) {
        this.rnaRefPseudo = value;
    }

    /**
     * Gets the value of the rnaRefExt property.
     * 
     * @return
     *     possible object is
     *     {@link RNARef.RNARefExt }
     *     
     */
    public RNARef.RNARefExt getRNARefExt() {
        return rnaRefExt;
    }

    /**
     * Sets the value of the rnaRefExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link RNARef.RNARefExt }
     *     
     */
    public void setRNARefExt(RNARef.RNARefExt value) {
        this.rnaRefExt = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="RNA-ref_ext_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RNA-ref_ext_tRNA">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Trna-ext"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="RNA-ref_ext_gen">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}RNA-gen"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rnaRefExtName",
        "rnaRefExtTRNA",
        "rnaRefExtGen"
    })
    public static class RNARefExt {

        @XmlElement(name = "RNA-ref_ext_name")
        protected String rnaRefExtName;
        @XmlElement(name = "RNA-ref_ext_tRNA")
        protected RNARef.RNARefExt.RNARefExtTRNA rnaRefExtTRNA;
        @XmlElement(name = "RNA-ref_ext_gen")
        protected RNARef.RNARefExt.RNARefExtGen rnaRefExtGen;

        /**
         * Gets the value of the rnaRefExtName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRNARefExtName() {
            return rnaRefExtName;
        }

        /**
         * Sets the value of the rnaRefExtName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRNARefExtName(String value) {
            this.rnaRefExtName = value;
        }

        /**
         * Gets the value of the rnaRefExtTRNA property.
         * 
         * @return
         *     possible object is
         *     {@link RNARef.RNARefExt.RNARefExtTRNA }
         *     
         */
        public RNARef.RNARefExt.RNARefExtTRNA getRNARefExtTRNA() {
            return rnaRefExtTRNA;
        }

        /**
         * Sets the value of the rnaRefExtTRNA property.
         * 
         * @param value
         *     allowed object is
         *     {@link RNARef.RNARefExt.RNARefExtTRNA }
         *     
         */
        public void setRNARefExtTRNA(RNARef.RNARefExt.RNARefExtTRNA value) {
            this.rnaRefExtTRNA = value;
        }

        /**
         * Gets the value of the rnaRefExtGen property.
         * 
         * @return
         *     possible object is
         *     {@link RNARef.RNARefExt.RNARefExtGen }
         *     
         */
        public RNARef.RNARefExt.RNARefExtGen getRNARefExtGen() {
            return rnaRefExtGen;
        }

        /**
         * Sets the value of the rnaRefExtGen property.
         * 
         * @param value
         *     allowed object is
         *     {@link RNARef.RNARefExt.RNARefExtGen }
         *     
         */
        public void setRNARefExtGen(RNARef.RNARefExt.RNARefExtGen value) {
            this.rnaRefExtGen = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}RNA-gen"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rnaGen"
        })
        public static class RNARefExtGen {

            @XmlElement(name = "RNA-gen", required = true)
            protected RNAGen rnaGen;

            /**
             * Gets the value of the rnaGen property.
             * 
             * @return
             *     possible object is
             *     {@link RNAGen }
             *     
             */
            public RNAGen getRNAGen() {
                return rnaGen;
            }

            /**
             * Sets the value of the rnaGen property.
             * 
             * @param value
             *     allowed object is
             *     {@link RNAGen }
             *     
             */
            public void setRNAGen(RNAGen value) {
                this.rnaGen = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Trna-ext"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "trnaExt"
        })
        public static class RNARefExtTRNA {

            @XmlElement(name = "Trna-ext", required = true)
            protected TrnaExt trnaExt;

            /**
             * Gets the value of the trnaExt property.
             * 
             * @return
             *     possible object is
             *     {@link TrnaExt }
             *     
             */
            public TrnaExt getTrnaExt() {
                return trnaExt;
            }

            /**
             * Sets the value of the trnaExt property.
             * 
             * @param value
             *     allowed object is
             *     {@link TrnaExt }
             *     
             */
            public void setTrnaExt(TrnaExt value) {
                this.trnaExt = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="true"/>
     *             &lt;enumeration value="false"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RNARefPseudo {

        @XmlAttribute(name = "value", required = true)
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="unknown"/>
     *             &lt;enumeration value="premsg"/>
     *             &lt;enumeration value="mRNA"/>
     *             &lt;enumeration value="tRNA"/>
     *             &lt;enumeration value="rRNA"/>
     *             &lt;enumeration value="snRNA"/>
     *             &lt;enumeration value="scRNA"/>
     *             &lt;enumeration value="snoRNA"/>
     *             &lt;enumeration value="ncRNA"/>
     *             &lt;enumeration value="tmRNA"/>
     *             &lt;enumeration value="miscRNA"/>
     *             &lt;enumeration value="other"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RNARefType {

        @XmlAttribute(name = "value", required = true)
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
