//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Seq-align_type">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="not-set"/>
 *                       &lt;enumeration value="global"/>
 *                       &lt;enumeration value="diags"/>
 *                       &lt;enumeration value="partial"/>
 *                       &lt;enumeration value="disc"/>
 *                       &lt;enumeration value="other"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Seq-align_dim" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Seq-align_score" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Score"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Seq-align_segs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Seq-align_segs_dendiag">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element ref="{http://www.ncbi.nlm.nih.gov}Dense-diag"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Seq-align_segs_denseg">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.ncbi.nlm.nih.gov}Dense-seg"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Seq-align_segs_std">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element ref="{http://www.ncbi.nlm.nih.gov}Std-seg"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Seq-align_segs_packed">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.ncbi.nlm.nih.gov}Packed-seg"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Seq-align_segs_disc">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.ncbi.nlm.nih.gov}Seq-align-set"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Seq-align_segs_spliced">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.ncbi.nlm.nih.gov}Spliced-seg"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Seq-align_segs_sparse">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.ncbi.nlm.nih.gov}Sparse-seg"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Seq-align_bounds" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Seq-loc"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Seq-align_id" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Object-id"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Seq-align_ext" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}User-object"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seqAlignType",
    "seqAlignDim",
    "seqAlignScore",
    "seqAlignSegs",
    "seqAlignBounds",
    "seqAlignId",
    "seqAlignExt"
})
@XmlRootElement(name = "Seq-align")
public class SeqAlign {

    @XmlElement(name = "Seq-align_type", required = true)
    protected SeqAlign.SeqAlignType seqAlignType;
    @XmlElement(name = "Seq-align_dim")
    protected BigInteger seqAlignDim;
    @XmlElement(name = "Seq-align_score")
    protected SeqAlign.SeqAlignScore seqAlignScore;
    @XmlElement(name = "Seq-align_segs", required = true)
    protected SeqAlign.SeqAlignSegs seqAlignSegs;
    @XmlElement(name = "Seq-align_bounds")
    protected SeqAlign.SeqAlignBounds seqAlignBounds;
    @XmlElement(name = "Seq-align_id")
    protected SeqAlign.SeqAlignId seqAlignId;
    @XmlElement(name = "Seq-align_ext")
    protected SeqAlign.SeqAlignExt seqAlignExt;

    /**
     * Gets the value of the seqAlignType property.
     * 
     * @return
     *     possible object is
     *     {@link SeqAlign.SeqAlignType }
     *     
     */
    public SeqAlign.SeqAlignType getSeqAlignType() {
        return seqAlignType;
    }

    /**
     * Sets the value of the seqAlignType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqAlign.SeqAlignType }
     *     
     */
    public void setSeqAlignType(SeqAlign.SeqAlignType value) {
        this.seqAlignType = value;
    }

    /**
     * Gets the value of the seqAlignDim property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeqAlignDim() {
        return seqAlignDim;
    }

    /**
     * Sets the value of the seqAlignDim property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeqAlignDim(BigInteger value) {
        this.seqAlignDim = value;
    }

    /**
     * Gets the value of the seqAlignScore property.
     * 
     * @return
     *     possible object is
     *     {@link SeqAlign.SeqAlignScore }
     *     
     */
    public SeqAlign.SeqAlignScore getSeqAlignScore() {
        return seqAlignScore;
    }

    /**
     * Sets the value of the seqAlignScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqAlign.SeqAlignScore }
     *     
     */
    public void setSeqAlignScore(SeqAlign.SeqAlignScore value) {
        this.seqAlignScore = value;
    }

    /**
     * Gets the value of the seqAlignSegs property.
     * 
     * @return
     *     possible object is
     *     {@link SeqAlign.SeqAlignSegs }
     *     
     */
    public SeqAlign.SeqAlignSegs getSeqAlignSegs() {
        return seqAlignSegs;
    }

    /**
     * Sets the value of the seqAlignSegs property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqAlign.SeqAlignSegs }
     *     
     */
    public void setSeqAlignSegs(SeqAlign.SeqAlignSegs value) {
        this.seqAlignSegs = value;
    }

    /**
     * Gets the value of the seqAlignBounds property.
     * 
     * @return
     *     possible object is
     *     {@link SeqAlign.SeqAlignBounds }
     *     
     */
    public SeqAlign.SeqAlignBounds getSeqAlignBounds() {
        return seqAlignBounds;
    }

    /**
     * Sets the value of the seqAlignBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqAlign.SeqAlignBounds }
     *     
     */
    public void setSeqAlignBounds(SeqAlign.SeqAlignBounds value) {
        this.seqAlignBounds = value;
    }

    /**
     * Gets the value of the seqAlignId property.
     * 
     * @return
     *     possible object is
     *     {@link SeqAlign.SeqAlignId }
     *     
     */
    public SeqAlign.SeqAlignId getSeqAlignId() {
        return seqAlignId;
    }

    /**
     * Sets the value of the seqAlignId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqAlign.SeqAlignId }
     *     
     */
    public void setSeqAlignId(SeqAlign.SeqAlignId value) {
        this.seqAlignId = value;
    }

    /**
     * Gets the value of the seqAlignExt property.
     * 
     * @return
     *     possible object is
     *     {@link SeqAlign.SeqAlignExt }
     *     
     */
    public SeqAlign.SeqAlignExt getSeqAlignExt() {
        return seqAlignExt;
    }

    /**
     * Sets the value of the seqAlignExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqAlign.SeqAlignExt }
     *     
     */
    public void setSeqAlignExt(SeqAlign.SeqAlignExt value) {
        this.seqAlignExt = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Seq-loc"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "seqLoc"
    })
    public static class SeqAlignBounds {

        @XmlElement(name = "Seq-loc")
        protected List<SeqLoc> seqLoc;

        /**
         * Gets the value of the seqLoc property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the seqLoc property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSeqLoc().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SeqLoc }
         * 
         * 
         */
        public List<SeqLoc> getSeqLoc() {
            if (seqLoc == null) {
                seqLoc = new ArrayList<SeqLoc>();
            }
            return this.seqLoc;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}User-object"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userObject"
    })
    public static class SeqAlignExt {

        @XmlElement(name = "User-object")
        protected List<UserObject> userObject;

        /**
         * Gets the value of the userObject property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userObject property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserObject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserObject }
         * 
         * 
         */
        public List<UserObject> getUserObject() {
            if (userObject == null) {
                userObject = new ArrayList<UserObject>();
            }
            return this.userObject;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Object-id"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "objectId"
    })
    public static class SeqAlignId {

        @XmlElement(name = "Object-id")
        protected List<ObjectId> objectId;

        /**
         * Gets the value of the objectId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the objectId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObjectId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObjectId }
         * 
         * 
         */
        public List<ObjectId> getObjectId() {
            if (objectId == null) {
                objectId = new ArrayList<ObjectId>();
            }
            return this.objectId;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Score"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "score"
    })
    public static class SeqAlignScore {

        @XmlElement(name = "Score")
        protected List<Score> score;

        /**
         * Gets the value of the score property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the score property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getScore().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Score }
         * 
         * 
         */
        public List<Score> getScore() {
            if (score == null) {
                score = new ArrayList<Score>();
            }
            return this.score;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Seq-align_segs_dendiag">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Dense-diag"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Seq-align_segs_denseg">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Dense-seg"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Seq-align_segs_std">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Std-seg"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Seq-align_segs_packed">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Packed-seg"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Seq-align_segs_disc">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Seq-align-set"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Seq-align_segs_spliced">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Spliced-seg"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Seq-align_segs_sparse">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Sparse-seg"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "seqAlignSegsDendiag",
        "seqAlignSegsDenseg",
        "seqAlignSegsStd",
        "seqAlignSegsPacked",
        "seqAlignSegsDisc",
        "seqAlignSegsSpliced",
        "seqAlignSegsSparse"
    })
    public static class SeqAlignSegs {

        @XmlElement(name = "Seq-align_segs_dendiag")
        protected SeqAlign.SeqAlignSegs.SeqAlignSegsDendiag seqAlignSegsDendiag;
        @XmlElement(name = "Seq-align_segs_denseg")
        protected SeqAlign.SeqAlignSegs.SeqAlignSegsDenseg seqAlignSegsDenseg;
        @XmlElement(name = "Seq-align_segs_std")
        protected SeqAlign.SeqAlignSegs.SeqAlignSegsStd seqAlignSegsStd;
        @XmlElement(name = "Seq-align_segs_packed")
        protected SeqAlign.SeqAlignSegs.SeqAlignSegsPacked seqAlignSegsPacked;
        @XmlElement(name = "Seq-align_segs_disc")
        protected SeqAlign.SeqAlignSegs.SeqAlignSegsDisc seqAlignSegsDisc;
        @XmlElement(name = "Seq-align_segs_spliced")
        protected SeqAlign.SeqAlignSegs.SeqAlignSegsSpliced seqAlignSegsSpliced;
        @XmlElement(name = "Seq-align_segs_sparse")
        protected SeqAlign.SeqAlignSegs.SeqAlignSegsSparse seqAlignSegsSparse;

        /**
         * Gets the value of the seqAlignSegsDendiag property.
         * 
         * @return
         *     possible object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsDendiag }
         *     
         */
        public SeqAlign.SeqAlignSegs.SeqAlignSegsDendiag getSeqAlignSegsDendiag() {
            return seqAlignSegsDendiag;
        }

        /**
         * Sets the value of the seqAlignSegsDendiag property.
         * 
         * @param value
         *     allowed object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsDendiag }
         *     
         */
        public void setSeqAlignSegsDendiag(SeqAlign.SeqAlignSegs.SeqAlignSegsDendiag value) {
            this.seqAlignSegsDendiag = value;
        }

        /**
         * Gets the value of the seqAlignSegsDenseg property.
         * 
         * @return
         *     possible object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsDenseg }
         *     
         */
        public SeqAlign.SeqAlignSegs.SeqAlignSegsDenseg getSeqAlignSegsDenseg() {
            return seqAlignSegsDenseg;
        }

        /**
         * Sets the value of the seqAlignSegsDenseg property.
         * 
         * @param value
         *     allowed object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsDenseg }
         *     
         */
        public void setSeqAlignSegsDenseg(SeqAlign.SeqAlignSegs.SeqAlignSegsDenseg value) {
            this.seqAlignSegsDenseg = value;
        }

        /**
         * Gets the value of the seqAlignSegsStd property.
         * 
         * @return
         *     possible object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsStd }
         *     
         */
        public SeqAlign.SeqAlignSegs.SeqAlignSegsStd getSeqAlignSegsStd() {
            return seqAlignSegsStd;
        }

        /**
         * Sets the value of the seqAlignSegsStd property.
         * 
         * @param value
         *     allowed object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsStd }
         *     
         */
        public void setSeqAlignSegsStd(SeqAlign.SeqAlignSegs.SeqAlignSegsStd value) {
            this.seqAlignSegsStd = value;
        }

        /**
         * Gets the value of the seqAlignSegsPacked property.
         * 
         * @return
         *     possible object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsPacked }
         *     
         */
        public SeqAlign.SeqAlignSegs.SeqAlignSegsPacked getSeqAlignSegsPacked() {
            return seqAlignSegsPacked;
        }

        /**
         * Sets the value of the seqAlignSegsPacked property.
         * 
         * @param value
         *     allowed object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsPacked }
         *     
         */
        public void setSeqAlignSegsPacked(SeqAlign.SeqAlignSegs.SeqAlignSegsPacked value) {
            this.seqAlignSegsPacked = value;
        }

        /**
         * Gets the value of the seqAlignSegsDisc property.
         * 
         * @return
         *     possible object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsDisc }
         *     
         */
        public SeqAlign.SeqAlignSegs.SeqAlignSegsDisc getSeqAlignSegsDisc() {
            return seqAlignSegsDisc;
        }

        /**
         * Sets the value of the seqAlignSegsDisc property.
         * 
         * @param value
         *     allowed object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsDisc }
         *     
         */
        public void setSeqAlignSegsDisc(SeqAlign.SeqAlignSegs.SeqAlignSegsDisc value) {
            this.seqAlignSegsDisc = value;
        }

        /**
         * Gets the value of the seqAlignSegsSpliced property.
         * 
         * @return
         *     possible object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsSpliced }
         *     
         */
        public SeqAlign.SeqAlignSegs.SeqAlignSegsSpliced getSeqAlignSegsSpliced() {
            return seqAlignSegsSpliced;
        }

        /**
         * Sets the value of the seqAlignSegsSpliced property.
         * 
         * @param value
         *     allowed object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsSpliced }
         *     
         */
        public void setSeqAlignSegsSpliced(SeqAlign.SeqAlignSegs.SeqAlignSegsSpliced value) {
            this.seqAlignSegsSpliced = value;
        }

        /**
         * Gets the value of the seqAlignSegsSparse property.
         * 
         * @return
         *     possible object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsSparse }
         *     
         */
        public SeqAlign.SeqAlignSegs.SeqAlignSegsSparse getSeqAlignSegsSparse() {
            return seqAlignSegsSparse;
        }

        /**
         * Sets the value of the seqAlignSegsSparse property.
         * 
         * @param value
         *     allowed object is
         *     {@link SeqAlign.SeqAlignSegs.SeqAlignSegsSparse }
         *     
         */
        public void setSeqAlignSegsSparse(SeqAlign.SeqAlignSegs.SeqAlignSegsSparse value) {
            this.seqAlignSegsSparse = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
         *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Dense-diag"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "denseDiag"
        })
        public static class SeqAlignSegsDendiag {

            @XmlElement(name = "Dense-diag")
            protected List<DenseDiag> denseDiag;

            /**
             * Gets the value of the denseDiag property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the denseDiag property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDenseDiag().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DenseDiag }
             * 
             * 
             */
            public List<DenseDiag> getDenseDiag() {
                if (denseDiag == null) {
                    denseDiag = new ArrayList<DenseDiag>();
                }
                return this.denseDiag;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Dense-seg"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "denseSeg"
        })
        public static class SeqAlignSegsDenseg {

            @XmlElement(name = "Dense-seg", required = true)
            protected DenseSeg denseSeg;

            /**
             * Gets the value of the denseSeg property.
             * 
             * @return
             *     possible object is
             *     {@link DenseSeg }
             *     
             */
            public DenseSeg getDenseSeg() {
                return denseSeg;
            }

            /**
             * Sets the value of the denseSeg property.
             * 
             * @param value
             *     allowed object is
             *     {@link DenseSeg }
             *     
             */
            public void setDenseSeg(DenseSeg value) {
                this.denseSeg = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Seq-align-set"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "seqAlignSet"
        })
        public static class SeqAlignSegsDisc {

            @XmlElement(name = "Seq-align-set", required = true)
            protected SeqAlignSet seqAlignSet;

            /**
             * Gets the value of the seqAlignSet property.
             * 
             * @return
             *     possible object is
             *     {@link SeqAlignSet }
             *     
             */
            public SeqAlignSet getSeqAlignSet() {
                return seqAlignSet;
            }

            /**
             * Sets the value of the seqAlignSet property.
             * 
             * @param value
             *     allowed object is
             *     {@link SeqAlignSet }
             *     
             */
            public void setSeqAlignSet(SeqAlignSet value) {
                this.seqAlignSet = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Packed-seg"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "packedSeg"
        })
        public static class SeqAlignSegsPacked {

            @XmlElement(name = "Packed-seg", required = true)
            protected PackedSeg packedSeg;

            /**
             * Gets the value of the packedSeg property.
             * 
             * @return
             *     possible object is
             *     {@link PackedSeg }
             *     
             */
            public PackedSeg getPackedSeg() {
                return packedSeg;
            }

            /**
             * Sets the value of the packedSeg property.
             * 
             * @param value
             *     allowed object is
             *     {@link PackedSeg }
             *     
             */
            public void setPackedSeg(PackedSeg value) {
                this.packedSeg = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Sparse-seg"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sparseSeg"
        })
        public static class SeqAlignSegsSparse {

            @XmlElement(name = "Sparse-seg", required = true)
            protected SparseSeg sparseSeg;

            /**
             * Gets the value of the sparseSeg property.
             * 
             * @return
             *     possible object is
             *     {@link SparseSeg }
             *     
             */
            public SparseSeg getSparseSeg() {
                return sparseSeg;
            }

            /**
             * Sets the value of the sparseSeg property.
             * 
             * @param value
             *     allowed object is
             *     {@link SparseSeg }
             *     
             */
            public void setSparseSeg(SparseSeg value) {
                this.sparseSeg = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Spliced-seg"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "splicedSeg"
        })
        public static class SeqAlignSegsSpliced {

            @XmlElement(name = "Spliced-seg", required = true)
            protected SplicedSeg splicedSeg;

            /**
             * Gets the value of the splicedSeg property.
             * 
             * @return
             *     possible object is
             *     {@link SplicedSeg }
             *     
             */
            public SplicedSeg getSplicedSeg() {
                return splicedSeg;
            }

            /**
             * Sets the value of the splicedSeg property.
             * 
             * @param value
             *     allowed object is
             *     {@link SplicedSeg }
             *     
             */
            public void setSplicedSeg(SplicedSeg value) {
                this.splicedSeg = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
         *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Std-seg"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "stdSeg"
        })
        public static class SeqAlignSegsStd {

            @XmlElement(name = "Std-seg")
            protected List<StdSeg> stdSeg;

            /**
             * Gets the value of the stdSeg property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the stdSeg property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getStdSeg().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link StdSeg }
             * 
             * 
             */
            public List<StdSeg> getStdSeg() {
                if (stdSeg == null) {
                    stdSeg = new ArrayList<StdSeg>();
                }
                return this.stdSeg;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="not-set"/>
     *             &lt;enumeration value="global"/>
     *             &lt;enumeration value="diags"/>
     *             &lt;enumeration value="partial"/>
     *             &lt;enumeration value="disc"/>
     *             &lt;enumeration value="other"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SeqAlignType {

        @XmlAttribute(name = "value", required = true)
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
