//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SeqFeatXref_id" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Feat-id"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SeqFeatXref_data" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}SeqFeatData"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seqFeatXrefId",
    "seqFeatXrefData"
})
@XmlRootElement(name = "SeqFeatXref")
public class SeqFeatXref {

    @XmlElement(name = "SeqFeatXref_id")
    protected SeqFeatXref.SeqFeatXrefId seqFeatXrefId;
    @XmlElement(name = "SeqFeatXref_data")
    protected SeqFeatXref.SeqFeatXrefData seqFeatXrefData;

    /**
     * Gets the value of the seqFeatXrefId property.
     * 
     * @return
     *     possible object is
     *     {@link SeqFeatXref.SeqFeatXrefId }
     *     
     */
    public SeqFeatXref.SeqFeatXrefId getSeqFeatXrefId() {
        return seqFeatXrefId;
    }

    /**
     * Sets the value of the seqFeatXrefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqFeatXref.SeqFeatXrefId }
     *     
     */
    public void setSeqFeatXrefId(SeqFeatXref.SeqFeatXrefId value) {
        this.seqFeatXrefId = value;
    }

    /**
     * Gets the value of the seqFeatXrefData property.
     * 
     * @return
     *     possible object is
     *     {@link SeqFeatXref.SeqFeatXrefData }
     *     
     */
    public SeqFeatXref.SeqFeatXrefData getSeqFeatXrefData() {
        return seqFeatXrefData;
    }

    /**
     * Sets the value of the seqFeatXrefData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqFeatXref.SeqFeatXrefData }
     *     
     */
    public void setSeqFeatXrefData(SeqFeatXref.SeqFeatXrefData value) {
        this.seqFeatXrefData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}SeqFeatData"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "seqFeatData"
    })
    public static class SeqFeatXrefData {

        @XmlElement(name = "SeqFeatData", required = true)
        protected SeqFeatData seqFeatData;

        /**
         * Gets the value of the seqFeatData property.
         * 
         * @return
         *     possible object is
         *     {@link SeqFeatData }
         *     
         */
        public SeqFeatData getSeqFeatData() {
            return seqFeatData;
        }

        /**
         * Sets the value of the seqFeatData property.
         * 
         * @param value
         *     allowed object is
         *     {@link SeqFeatData }
         *     
         */
        public void setSeqFeatData(SeqFeatData value) {
            this.seqFeatData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Feat-id"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "featId"
    })
    public static class SeqFeatXrefId {

        @XmlElement(name = "Feat-id", required = true)
        protected FeatId featId;

        /**
         * Gets the value of the featId property.
         * 
         * @return
         *     possible object is
         *     {@link FeatId }
         *     
         */
        public FeatId getFeatId() {
            return featId;
        }

        /**
         * Sets the value of the featId property.
         * 
         * @param value
         *     allowed object is
         *     {@link FeatId }
         *     
         */
        public void setFeatId(FeatId value) {
            this.featId = value;
        }

    }

}
