//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Seq-point_point" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Seq-point_strand" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Na-strand"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Seq-point_id">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Seq-id"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Seq-point_fuzz" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Int-fuzz"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seqPointPoint",
    "seqPointStrand",
    "seqPointId",
    "seqPointFuzz"
})
@XmlRootElement(name = "Seq-point")
public class SeqPoint {

    @XmlElement(name = "Seq-point_point", required = true)
    protected BigInteger seqPointPoint;
    @XmlElement(name = "Seq-point_strand")
    protected SeqPoint.SeqPointStrand seqPointStrand;
    @XmlElement(name = "Seq-point_id", required = true)
    protected SeqPoint.SeqPointId seqPointId;
    @XmlElement(name = "Seq-point_fuzz")
    protected SeqPoint.SeqPointFuzz seqPointFuzz;

    /**
     * Gets the value of the seqPointPoint property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeqPointPoint() {
        return seqPointPoint;
    }

    /**
     * Sets the value of the seqPointPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeqPointPoint(BigInteger value) {
        this.seqPointPoint = value;
    }

    /**
     * Gets the value of the seqPointStrand property.
     * 
     * @return
     *     possible object is
     *     {@link SeqPoint.SeqPointStrand }
     *     
     */
    public SeqPoint.SeqPointStrand getSeqPointStrand() {
        return seqPointStrand;
    }

    /**
     * Sets the value of the seqPointStrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqPoint.SeqPointStrand }
     *     
     */
    public void setSeqPointStrand(SeqPoint.SeqPointStrand value) {
        this.seqPointStrand = value;
    }

    /**
     * Gets the value of the seqPointId property.
     * 
     * @return
     *     possible object is
     *     {@link SeqPoint.SeqPointId }
     *     
     */
    public SeqPoint.SeqPointId getSeqPointId() {
        return seqPointId;
    }

    /**
     * Sets the value of the seqPointId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqPoint.SeqPointId }
     *     
     */
    public void setSeqPointId(SeqPoint.SeqPointId value) {
        this.seqPointId = value;
    }

    /**
     * Gets the value of the seqPointFuzz property.
     * 
     * @return
     *     possible object is
     *     {@link SeqPoint.SeqPointFuzz }
     *     
     */
    public SeqPoint.SeqPointFuzz getSeqPointFuzz() {
        return seqPointFuzz;
    }

    /**
     * Sets the value of the seqPointFuzz property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqPoint.SeqPointFuzz }
     *     
     */
    public void setSeqPointFuzz(SeqPoint.SeqPointFuzz value) {
        this.seqPointFuzz = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Int-fuzz"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "intFuzz"
    })
    public static class SeqPointFuzz {

        @XmlElement(name = "Int-fuzz", required = true)
        protected IntFuzz intFuzz;

        /**
         * Gets the value of the intFuzz property.
         * 
         * @return
         *     possible object is
         *     {@link IntFuzz }
         *     
         */
        public IntFuzz getIntFuzz() {
            return intFuzz;
        }

        /**
         * Sets the value of the intFuzz property.
         * 
         * @param value
         *     allowed object is
         *     {@link IntFuzz }
         *     
         */
        public void setIntFuzz(IntFuzz value) {
            this.intFuzz = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Seq-id"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "seqId"
    })
    public static class SeqPointId {

        @XmlElement(name = "Seq-id", required = true)
        protected SeqId seqId;

        /**
         * Gets the value of the seqId property.
         * 
         * @return
         *     possible object is
         *     {@link SeqId }
         *     
         */
        public SeqId getSeqId() {
            return seqId;
        }

        /**
         * Sets the value of the seqId property.
         * 
         * @param value
         *     allowed object is
         *     {@link SeqId }
         *     
         */
        public void setSeqId(SeqId value) {
            this.seqId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Na-strand"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naStrand"
    })
    public static class SeqPointStrand {

        @XmlElement(name = "Na-strand", required = true)
        protected NaStrand naStrand;

        /**
         * Gets the value of the naStrand property.
         * 
         * @return
         *     possible object is
         *     {@link NaStrand }
         *     
         */
        public NaStrand getNaStrand() {
            return naStrand;
        }

        /**
         * Sets the value of the naStrand property.
         * 
         * @param value
         *     allowed object is
         *     {@link NaStrand }
         *     
         */
        public void setNaStrand(NaStrand value) {
            this.naStrand = value;
        }

    }

}
