//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SeqTable-column-info_title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SeqTable-column-info_field-id" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
 *                 &lt;attribute name="value">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="location"/>
 *                       &lt;enumeration value="location-id"/>
 *                       &lt;enumeration value="location-gi"/>
 *                       &lt;enumeration value="location-from"/>
 *                       &lt;enumeration value="location-to"/>
 *                       &lt;enumeration value="location-strand"/>
 *                       &lt;enumeration value="location-fuzz-from-lim"/>
 *                       &lt;enumeration value="location-fuzz-to-lim"/>
 *                       &lt;enumeration value="product"/>
 *                       &lt;enumeration value="product-id"/>
 *                       &lt;enumeration value="product-gi"/>
 *                       &lt;enumeration value="product-from"/>
 *                       &lt;enumeration value="product-to"/>
 *                       &lt;enumeration value="product-strand"/>
 *                       &lt;enumeration value="product-fuzz-from-lim"/>
 *                       &lt;enumeration value="product-fuzz-to-lim"/>
 *                       &lt;enumeration value="id-local"/>
 *                       &lt;enumeration value="xref-id-local"/>
 *                       &lt;enumeration value="partial"/>
 *                       &lt;enumeration value="comment"/>
 *                       &lt;enumeration value="title"/>
 *                       &lt;enumeration value="ext"/>
 *                       &lt;enumeration value="qual"/>
 *                       &lt;enumeration value="dbxref"/>
 *                       &lt;enumeration value="data-imp-key"/>
 *                       &lt;enumeration value="data-region"/>
 *                       &lt;enumeration value="data-cdregion-frame"/>
 *                       &lt;enumeration value="ext-type"/>
 *                       &lt;enumeration value="qual-qual"/>
 *                       &lt;enumeration value="qual-val"/>
 *                       &lt;enumeration value="dbxref-db"/>
 *                       &lt;enumeration value="dbxref-tag"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SeqTable-column-info_field-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seqTableColumnInfoTitle",
    "seqTableColumnInfoFieldId",
    "seqTableColumnInfoFieldName"
})
@XmlRootElement(name = "SeqTable-column-info")
public class SeqTableColumnInfo {

    @XmlElement(name = "SeqTable-column-info_title")
    protected String seqTableColumnInfoTitle;
    @XmlElement(name = "SeqTable-column-info_field-id")
    protected SeqTableColumnInfo.SeqTableColumnInfoFieldId seqTableColumnInfoFieldId;
    @XmlElement(name = "SeqTable-column-info_field-name")
    protected String seqTableColumnInfoFieldName;

    /**
     * Gets the value of the seqTableColumnInfoTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqTableColumnInfoTitle() {
        return seqTableColumnInfoTitle;
    }

    /**
     * Sets the value of the seqTableColumnInfoTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqTableColumnInfoTitle(String value) {
        this.seqTableColumnInfoTitle = value;
    }

    /**
     * Gets the value of the seqTableColumnInfoFieldId property.
     * 
     * @return
     *     possible object is
     *     {@link SeqTableColumnInfo.SeqTableColumnInfoFieldId }
     *     
     */
    public SeqTableColumnInfo.SeqTableColumnInfoFieldId getSeqTableColumnInfoFieldId() {
        return seqTableColumnInfoFieldId;
    }

    /**
     * Sets the value of the seqTableColumnInfoFieldId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqTableColumnInfo.SeqTableColumnInfoFieldId }
     *     
     */
    public void setSeqTableColumnInfoFieldId(SeqTableColumnInfo.SeqTableColumnInfoFieldId value) {
        this.seqTableColumnInfoFieldId = value;
    }

    /**
     * Gets the value of the seqTableColumnInfoFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqTableColumnInfoFieldName() {
        return seqTableColumnInfoFieldName;
    }

    /**
     * Sets the value of the seqTableColumnInfoFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqTableColumnInfoFieldName(String value) {
        this.seqTableColumnInfoFieldName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
     *       &lt;attribute name="value">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="location"/>
     *             &lt;enumeration value="location-id"/>
     *             &lt;enumeration value="location-gi"/>
     *             &lt;enumeration value="location-from"/>
     *             &lt;enumeration value="location-to"/>
     *             &lt;enumeration value="location-strand"/>
     *             &lt;enumeration value="location-fuzz-from-lim"/>
     *             &lt;enumeration value="location-fuzz-to-lim"/>
     *             &lt;enumeration value="product"/>
     *             &lt;enumeration value="product-id"/>
     *             &lt;enumeration value="product-gi"/>
     *             &lt;enumeration value="product-from"/>
     *             &lt;enumeration value="product-to"/>
     *             &lt;enumeration value="product-strand"/>
     *             &lt;enumeration value="product-fuzz-from-lim"/>
     *             &lt;enumeration value="product-fuzz-to-lim"/>
     *             &lt;enumeration value="id-local"/>
     *             &lt;enumeration value="xref-id-local"/>
     *             &lt;enumeration value="partial"/>
     *             &lt;enumeration value="comment"/>
     *             &lt;enumeration value="title"/>
     *             &lt;enumeration value="ext"/>
     *             &lt;enumeration value="qual"/>
     *             &lt;enumeration value="dbxref"/>
     *             &lt;enumeration value="data-imp-key"/>
     *             &lt;enumeration value="data-region"/>
     *             &lt;enumeration value="data-cdregion-frame"/>
     *             &lt;enumeration value="ext-type"/>
     *             &lt;enumeration value="qual-qual"/>
     *             &lt;enumeration value="qual-val"/>
     *             &lt;enumeration value="dbxref-db"/>
     *             &lt;enumeration value="dbxref-tag"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class SeqTableColumnInfoFieldId {

        @XmlValue
        protected BigInteger value;
        @XmlAttribute(name = "value")
        protected String valueAttribute;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the valueAttribute property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValueAttribute() {
            return valueAttribute;
        }

        /**
         * Sets the value of the valueAttribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValueAttribute(String value) {
            this.valueAttribute = value;
        }

    }

}
