//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Seq-table_feat-type" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Seq-table_feat-subtype" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Seq-table_num-rows" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Seq-table_columns">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}SeqTable-column"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seqTableFeatType",
    "seqTableFeatSubtype",
    "seqTableNumRows",
    "seqTableColumns"
})
@XmlRootElement(name = "Seq-table")
public class SeqTable {

    @XmlElement(name = "Seq-table_feat-type", required = true)
    protected BigInteger seqTableFeatType;
    @XmlElement(name = "Seq-table_feat-subtype")
    protected BigInteger seqTableFeatSubtype;
    @XmlElement(name = "Seq-table_num-rows", required = true)
    protected BigInteger seqTableNumRows;
    @XmlElement(name = "Seq-table_columns", required = true)
    protected SeqTable.SeqTableColumns seqTableColumns;

    /**
     * Gets the value of the seqTableFeatType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeqTableFeatType() {
        return seqTableFeatType;
    }

    /**
     * Sets the value of the seqTableFeatType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeqTableFeatType(BigInteger value) {
        this.seqTableFeatType = value;
    }

    /**
     * Gets the value of the seqTableFeatSubtype property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeqTableFeatSubtype() {
        return seqTableFeatSubtype;
    }

    /**
     * Sets the value of the seqTableFeatSubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeqTableFeatSubtype(BigInteger value) {
        this.seqTableFeatSubtype = value;
    }

    /**
     * Gets the value of the seqTableNumRows property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeqTableNumRows() {
        return seqTableNumRows;
    }

    /**
     * Sets the value of the seqTableNumRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeqTableNumRows(BigInteger value) {
        this.seqTableNumRows = value;
    }

    /**
     * Gets the value of the seqTableColumns property.
     * 
     * @return
     *     possible object is
     *     {@link SeqTable.SeqTableColumns }
     *     
     */
    public SeqTable.SeqTableColumns getSeqTableColumns() {
        return seqTableColumns;
    }

    /**
     * Sets the value of the seqTableColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeqTable.SeqTableColumns }
     *     
     */
    public void setSeqTableColumns(SeqTable.SeqTableColumns value) {
        this.seqTableColumns = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}SeqTable-column"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "seqTableColumn"
    })
    public static class SeqTableColumns {

        @XmlElement(name = "SeqTable-column")
        protected List<SeqTableColumn> seqTableColumn;

        /**
         * Gets the value of the seqTableColumn property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the seqTableColumn property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSeqTableColumn().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SeqTableColumn }
         * 
         * 
         */
        public List<SeqTableColumn> getSeqTableColumn() {
            if (seqTableColumn == null) {
                seqTableColumn = new ArrayList<SeqTableColumn>();
            }
            return this.seqTableColumn;
        }

    }

}
