//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 09:24:32 PM PDT 
//


package gov.nih.nlm.ncbi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Spliced-exon-chunk_match" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Spliced-exon-chunk_mismatch" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Spliced-exon-chunk_diag" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Spliced-exon-chunk_product-ins" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Spliced-exon-chunk_genomic-ins" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "splicedExonChunkMatch",
    "splicedExonChunkMismatch",
    "splicedExonChunkDiag",
    "splicedExonChunkProductIns",
    "splicedExonChunkGenomicIns"
})
@XmlRootElement(name = "Spliced-exon-chunk")
public class SplicedExonChunk {

    @XmlElement(name = "Spliced-exon-chunk_match")
    protected BigInteger splicedExonChunkMatch;
    @XmlElement(name = "Spliced-exon-chunk_mismatch")
    protected BigInteger splicedExonChunkMismatch;
    @XmlElement(name = "Spliced-exon-chunk_diag")
    protected BigInteger splicedExonChunkDiag;
    @XmlElement(name = "Spliced-exon-chunk_product-ins")
    protected BigInteger splicedExonChunkProductIns;
    @XmlElement(name = "Spliced-exon-chunk_genomic-ins")
    protected BigInteger splicedExonChunkGenomicIns;

    /**
     * Gets the value of the splicedExonChunkMatch property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSplicedExonChunkMatch() {
        return splicedExonChunkMatch;
    }

    /**
     * Sets the value of the splicedExonChunkMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSplicedExonChunkMatch(BigInteger value) {
        this.splicedExonChunkMatch = value;
    }

    /**
     * Gets the value of the splicedExonChunkMismatch property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSplicedExonChunkMismatch() {
        return splicedExonChunkMismatch;
    }

    /**
     * Sets the value of the splicedExonChunkMismatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSplicedExonChunkMismatch(BigInteger value) {
        this.splicedExonChunkMismatch = value;
    }

    /**
     * Gets the value of the splicedExonChunkDiag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSplicedExonChunkDiag() {
        return splicedExonChunkDiag;
    }

    /**
     * Sets the value of the splicedExonChunkDiag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSplicedExonChunkDiag(BigInteger value) {
        this.splicedExonChunkDiag = value;
    }

    /**
     * Gets the value of the splicedExonChunkProductIns property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSplicedExonChunkProductIns() {
        return splicedExonChunkProductIns;
    }

    /**
     * Sets the value of the splicedExonChunkProductIns property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSplicedExonChunkProductIns(BigInteger value) {
        this.splicedExonChunkProductIns = value;
    }

    /**
     * Gets the value of the splicedExonChunkGenomicIns property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSplicedExonChunkGenomicIns() {
        return splicedExonChunkGenomicIns;
    }

    /**
     * Sets the value of the splicedExonChunkGenomicIns property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSplicedExonChunkGenomicIns(BigInteger value) {
        this.splicedExonChunkGenomicIns = value;
    }

}
